### ISSUE TITLE
Error on toolbox log

### ISSUE THREAD

**Issue by n-Faiz** [Snugglez/Auto-Bank#4]
[dispatch] [auto-bank] hook: deprecated definition (S_VIEW_WARE_EX.2), mod might be broken!

this error shows when opening bank. But the mod still works as normal
![image](https://user-images.githubusercontent.com/62085741/89592438-33d0f580-d87f-11ea-869c-5f4242e26f72.png)

**Comment by Snugglez** [comment]
Will be fixed later today once im back at pc

**Comment by Snugglez** [comment]
Should be fixed now
